services:
  backend:
    container_name: tunika

    build:
      context: .
      dockerfile: Dockerfile

    image: tunika:latest
    restart: unless-stopped
    env_file: .env

    volumes:
      - temp:/app/.tmp
      - public:/app/public/uploads

    ports:
      - '1337:1337'

volumes:
  temp:
  public: